export const homeData = [
    {
        id: 1,
        name: "Sand Dust",
        rating: 4.7,
        time: "2hr : 22mins",
        desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
        starring: "Karen Gilchrist, James Earl Jones",
        genres: "Action",
        tags: "Action, Adventures, Horror",
        cover:"https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/home%2Fhome1.jpg?alt=media&token=4b6a4cbd-db77-45e5-ba2c-8482b386345a",
        video: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/video%2FMIKE.mp4?alt=media&token=cb1bdec1-1948-49eb-ac82-7fb71fa154c0",
        date: "20-Jan-1997",
    },
    {
        id: 2,
        name: "skull island",
        rating: 4.6,
        time: "2hr : 22mins",
        desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
        starring: "Brenda Chapman, Jeff Nathanson",
        genres: "Adventures",
        tags: "Adventures,Animation,Family",
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/home%2Fhome2.jpg?alt=media&token=aea5174a-fc31-463e-bd74-8ad8dfaf2268",
        video: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/video%2FBlack%20Adam.mp4?alt=media&token=43d1f405-0231-4054-b1aa-6d6afffac545",
        date: "10-JUL-2021",
    },
    {
        id: 3,
        name: "Pirates Sea",
        rating: 4.8,
        time: "2hr : 22mins",
        desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
        starring: "James Chinlund, Jeff Nathanson",
        genres: "Adventures",
        tags: "Adventures,Action ",
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/home%2Fhome3.jpg?alt=media&token=41e80b1d-b642-46bf-b510-395f4379b835",
        video: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/video%2FThor.mp4?alt=media&token=e77e88fe-4392-4355-a51f-f2b26965a7b2",
        date: "20-FEB-2010",
    },
    {
        id: 4,
        name: "Shadow",
        rating: 4.9,
        time: "2hr : 22mins",
        desc:"Two feuding kingdoms in this centuries-old saga, Yan and Pen, have a peace treaty that stands as long as the King of Pei (Ryan Zheng) doesn’t attempt to reclaim a city lost in battle. A complacent cretin, the King agrees not to stir the waters, thus ensuring his throne won’t be taken from him. Nonetheless, Commander Yu (Deng Chao), Pei’s greatest hero, has gone ahead and set up a mortal duel with Yan’s General Yang (Hu Jun, “Lan Yu”)",
        starring: "Karen Gilchrist, James Earl Jones",
        genres: "Action",
        tags: "Action, Adventures, Horror",
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/home%2Fhome4.jpg?alt=media&token=72f25dae-1f8f-44a9-8a69-687387e646a6",
        video: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/video%2FBLONDE.mp4?alt=media&token=4a35efed-08bc-464a-ac0b-9fa5dbca4a03",
        date: "12-Aug-2015",
    },
]

export const upcome = [
    {
        id: 1,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu1.jpg?alt=media&token=116aeb2d-f1d8-46a1-8ba0-e44bbb3846df",
        name: "My office Boss",
        time: "2hr : 38mins",
    },
    {
        id: 2,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu2.jpg?alt=media&token=76226d0c-2900-402b-8b4b-ce592d6a449b",
        name: "Shadowe",
        time: "2hr : 38mins",
    },
    {
        id: 3,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu3.jpg?alt=media&token=085a26e3-d4c6-449f-a7b8-ba9719ff9948",
        name: "Another Danger",
        time: "2hr : 38mins",
    },
    {
        id: 4,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu4.jpg?alt=media&token=24057792-988f-4d70-a858-3c3813e7e670",
        name: "One Man Army",
        time: "2hr : 38mins",
    },
    {
        id: 5,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu5.jpg?alt=media&token=cb9ef485-69c6-4839-9c0e-eb240c53408f",
        name: "Jumbo Queen",
        time: "2hr : 38mins",
    },
]

export const latest = [
    {
        id: 1,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu6.png?alt=media&token=66135041-de88-447c-be3b-1399abaa53c3",
        name: "King of Jungle",
        time: "2hr : 38mins",
    },
    {
        id: 2,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu7.jpg?alt=media&token=94b92cc9-df65-42e7-b410-d43fd2f3f7e6",
        name: "The illusion",
        time: "2hr : 38mins",
    },
    {
        id: 3,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu3.jpg?alt=media&token=085a26e3-d4c6-449f-a7b8-ba9719ff9948",
        name: "Latest Movie",
        time: "2hr : 38mins",
    },
    {
        id: 4,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu4.jpg?alt=media&token=24057792-988f-4d70-a858-3c3813e7e670",
        name: "Latest two",
        time: "2hr : 38mins",
    },
    {
        id: 5,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/upcome%2Fu5.jpg?alt=media&token=cb9ef485-69c6-4839-9c0e-eb240c53408f",
        name: "Latest Three",
        time: "2hr : 38mins",
    },
]

export const trending = [
    {
        id: 1,
        name: "The Dinosaur",
        rating: 4.7,
        time: "2hr : 22mins",
        desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
        starring: "Karen Gilchrist, James Earl Jones",
        genres: "Action",
        tags: "Action, Adventures, Horror",
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/img%2Fslide1.png?alt=media&token=6c7576c5-95dd-462c-a625-e6c8243feff4",
        date: "20-Jan-1997",
    },
    {
        id: 2,
        name: "The Great Emperor",
        rating: 4.6,
        time: "2hr : 22mins",
        desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
        starring: "Brenda Chapman, Jeff Nathanson",
        genres: "Adventures",
        tags: "Adventures,Animation,Family",
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/img%2Fslide2.jpg?alt=media&token=1ad45e8e-9925-4c13-a6cc-ed82f1f318c2",
        date: "10-JUL-2021",
    },
    {
        id: 3,
        name: "Jumbo Queen",
        rating: 4.8,
        time: "2hr : 22mins",
        desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
        starring: "James Chinlund, Jeff Nathanson",
        genres: "Adventures",
        tags: "Adventures,Action ",
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/img%2Fslide3.jpg?alt=media&token=07ed098d-35ab-4f1f-965c-061f62b8f0f9",
        date: "20-FEB-2010",
    },
]

export const recommended = [
    {
        id: 4,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/rec%2Frec1.jpg?alt=media&token=d2ea2fdd-0158-4f99-acaf-80b8da8f2a03",
        name: "One Man Army",
        time: "2hr : 38mins",
    },
    {
        id: 5,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/rec%2Frec2.jpg?alt=media&token=e239f1a4-0eb3-470e-9c79-b4c69aa4978f",
        name: "Jumbo Queen",
        time: "2hr : 38mins",
    },
    {
        id: 1,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/rec%2Frec3.jpg?alt=media&token=4d0618e7-c67a-4977-86d5-0a62ecab1dea",
        name: "My office Boss",
        time: "2hr : 38mins",
    },
    {
        id: 2,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/rec%2Frec4.jpg?alt=media&token=9b3f3616-28e1-4801-a320-d820eca8e5b1",
        name: "Shadowe",
        time: "2hr : 38mins",
    },
    {
        id: 3,
        cover: "https://firebasestorage.googleapis.com/v0/b/movie-app-889ee.appspot.com/o/home%2Fhome1.jpg?alt=media&token=4b6a4cbd-db77-45e5-ba2c-8482b386345a",
        name: "Another Danger",
        time: "2hr : 38mins",
    },
]